//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCDMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NCD
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Block_name { get; set; }
        public string Date { get; set; }
        public string Does_his_or_her_BP_reading_systolic_140mm_Hg_or_higher_and_or_diastolic_90mm_Hg_or_higher_fall_under_hypertensive_range { get; set; }
        public string Does_his_or_her_RBS_reading_more_than_140mgdl_fall_under_diabetic_range { get; set; }
        public string Has_this_person_been_followed_up_by_NCD_Mitra { get; set; }
        public string Has_this_person_been_recommended_to_visit_the_PHC_to_consult_the_doctor { get; set; }
        public string Have_you_started_with_the_medication { get; set; }
        public string Household_ID { get; set; }
        public string Household_head_name { get; set; }
        public string Hypertension_reading { get; set; }
        public string If_yes_where_did_he_or_she_visit_for_the_check_up { get; set; }
        public string If_yes_whether_the_person_is_continuing_with_medication { get; set; }
        public string If_yes_whom_does_he_or_she_consults_for_medication { get; set; }
        public string Member_ID { get; set; }
        public string Member_name { get; set; }
        public string Member_or_household_head_Mobile_number { get; set; }
        public string NCD_volunteer_name { get; set; }
        public string Panchayat_name { get; set; }
        public string Random_blood_sugar_reading { get; set; }
        public string Sex { get; set; }
        public string Village_name { get; set; }
        public string What_was_the_result_of_check_up_by_a_medical_doctor { get; set; }
        public string Whether_the_NCD_mitra_has_asha_plus_device { get; set; }
        public string Whether_the_member_is_already_a_patient_of_diabetes { get; set; }
        public string Whether_the_member_is_already_a_patient_of_hypertension { get; set; }
        public string Whether_this_person_has_started_making_changes_in_their_dietary_habit { get; set; }
        public string Whether_this_person_has_started_regular_exercise_or_yoga { get; set; }
        public string Whether_this_person_has_started_with_destressing_practices { get; set; }
        public string Whether_this_person_has_taking_8_hours_of_sound_sleep { get; set; }
        public string Whether_this_person_has_visited_Sub_centre_or_Primary_Health_Centre_for_blood_sugar_screening_by_a_medical_doctor { get; set; }
        public string Whether_this_person_has_visited_Subcentre_or_Primary_Health_Centre_for_BP_screening_by_a_medical_doctor { get; set; }
        public string UniqueKey { get; set; }
        public Nullable<bool> IsAtcive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
